# runtime: go121
# instance_class: f1
# automatic_scaling:
#   target_cpu_utilization: 0.65
#
# service: default
# handlers:
# - url: /static
#   static_dir: TylerAldrich.dev/build/static
#
# - url: /.*
#   static_files: TylerAldrich.dev/build/index.html
#   upload: TylerAldrich.dev/build/index.html
#
# service: backend-api
# runtime: go120
# entrypoint: go run main.go
#
# handlers:
# - url: /.*
#   script: auto
