name: Update Firebase on Push

on:
  push:
    branches:
      - main

jobs:
  update-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          firebase login: ci --no-localhost --open-sso
          firebase deploy --only storage
        env:
          FIREBASE_TOKEN ${{ secrets.FIREBASE_PORTFOLIO_TOKEN }}

