name: Upload to Firebase Storage

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.FIREBASE_KEY }}
        export_default_credentials: true
    - name: Authenticate with Firebase
      run: gcloud auth activate-service-account --key-file=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    - name: Upload to Firebase Storage
      run: |
        gsutil -m cp -r ./src/* gs://aldrich-dev-portfolio.appspot.com/projects/portfolio

